version: "3.9"
services:
  product:
    build: ./product
    container_name: ecomm-product
    ports:
      - 3001:3001
    volumes:
      - ./product/:/app/
    depends_on:
      - mongo
  
  account:
    build: ./account
    container_name: ecomm-account
    ports:
      - 3002:3002
    volumes:
      - ./account/:/app/
    depends_on:
      - mongo
  
  order:
    build: ./order
    container_name: ecomm-order
    ports:
      - 3003:3003
    volumes:
      - ./order/:/app/
    depends_on:
      - mongo

  finance:
    build: ./finance
    container_name: ecomm-finance
    ports:
      - 3004:3004
    volumes:
      - ./finance/:/app/
    depends_on:
      - mysql

  mongo:
    image: mongo
    container_name: ecomm-mongo
    volumes:
      - db-mongo-ecomm:/data/db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret

  mysql:
    image: mysql
    container_name: ecomm-mysql
    volumes:
      - db-mysql-ecomm:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret

  redis:
    image: redis
    container_name: redis-ecomm
    volumes:
    - redis_data:/data
    restart: always
    ports:
    - 6379:6379

volumes:
  db-mongo-ecomm:
  db-mysql-ecomm:
  redis_data:
