version: "3.9"
services:
  product:
    build: ./product
    ports:
      - 3001:3001
    container_name: ecomm-product
  
  account:
    build: ./account
    ports:
      - 3002:3002
    container_name: ecomm-account

  mongo:
    container_name: mongo-ecomm
    image: mongo
    volumes:
      - db-mongo-ecomm:/data/db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret

volumes:
  db-mongo-ecomm:
